<a href="https://colab.research.google.com/github/deangarcia/NLP/blob/main/NaiveBayesMultiLabelClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First what I need to do is find the probablity of the types of each poem so the ratio of love and all poems then the probability of Mythology and Folklore and probability of Nature. Then for each of those subsets I need to calculate the probability of each word occuring given that it is of a particular class. Than we see which proability is higher whichever is higher is the class.

How do I take into account the title and author? should I just merge them? I could try both merging them and then also taking into account the probabilities.

In [61]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

print(X.toarray())


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
!pip install datasets

So I have the vectorized counts of the words and all the contents, need to find the raw probability based off my examples from the merve dataset now I need to aggregate the author and the tile. Then take the counts and create another matrix for the probability value which is the counts over the total number of words in the vocab. Hard part with this is that the raw probability will have a huge weight on what the result will be. Could do unigram and bigram version of this too.



In [ ]:
from datasets import load_dataset
import numpy as np
dataset = load_dataset("merve/poetry")

corpus = []
for group in dataset:
  for attributes in dataset:
    #print(dataset[attributes])
    for content in dataset[attributes]:
      #print(content['content'])
      corpus.append(content['content'])

vectorizer = CountVectorizer() # what is the default tokenizer understand this more
X = vectorizer.fit_transform(corpus) # figure out how this works 
vocab = vectorizer.get_feature_names()
word_count_vectors = []
#print(vocab)
# go through the vocab and the remove any words that do not occur more than X amount of times lets say 3 replace with <UNK>
# review this link to do this https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

#for counts in X.toarray()[150:155]:
for counts in X.toarray():
  word_count_vectors.append(list(np.asarray(counts) + 1))


# Need to figure out how to make it so that the raw probability of it being a specific type doesnt overshadow the probabilities of the words occuring.
#for counts in word_count_vectors:
  #print(counts)
